export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const OPEN_TODO = 'OPEN_TODO'
export const CHANGE_TODO = 'CHANGE_TODO'
export const ADD_MARK = 'ADD_MARK'

export const FETCH_TODOS = 'FETCH_TODOS'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
export const SHOW_ERROR = 'SHOW_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'